name: jsonnet

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./
